apiVersion: v1
kind: ConfigMap
metadata:
  name: rate-limit-exam-conf
  namespace: default
data:
  nginx.conf: |
    user  nginx;
    worker_processes  2;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        #sendfile        on;
        #tcp_nopush     on;
        #keepalive_timeout  65;
        #gzip  on;
        #include /etc/nginx/conf.d/*.conf;

        limit_req_zone $binary_remote_addr zone=test:10m rate=100r/s;

        server {
            listen 80;
            server_name localhost;
            location /status {
                limit_req_status    400;
                #limit_req zone=test burst=100;
                limit_req zone=test burst=100 nodelay;
                stub_status on;
                allow all;
                deny all;
            }

            #location /sleep {
            #    #content_by_lua 'os.execute("/tmp/sleep.sh")';
            #    content_by_lua_block {
            #        os.exec("bash /tmp/sleep.sh");
            #    }
            #}
        }
    }
  sleep.sh: |
    #!/bin/bash

    sleep 0.5
