apiVersion: v1
kind: Pod
metadata:
  name: rate-limit-exam-pod
  labels:
    app: rate-limit-exam-pod
spec:
  containers:
    - name: rate-limit-exam
      image: nginx:1.19
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: sleep-sh
          mountPath: /tmp/sleep.sh
          readOnly: true
  volumes:
    - name: nginx-conf
      configMap:
        name: rate-limit-exam-conf
        items:
          - key: nginx.conf
            path: nginx.conf
    - name: sleep-sh
      configMap:
        name: rate-limit-exam-conf
        items:
          - key: sleep.sh
            path: sleep.sh

