apiVersion: v1
kind: Service
metadata:
  name: rate-limit-exam-service
spec:
  type: NodePort
  selector:
    app: rate-limit-exam-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32222